const financialGridColumns: [key: string, label: string][] = [
    ["totalRevenue", "Total revenue"],
    ["costOfRevenue", "Cost of revenue"],
    ["grossProfit", "Gross profit"],
    ["operatingExpense", "Operating expense"],
    ["operatingIncome", "Operating income"],
    ["netNonOperatingInterestIncomeExpense", "Net non-operating interest income/expense"],
    ["otherIncomeExpense", "Other income/expense"],
    ["preTaxIncome", "Pre-tax income"],
    ["taxProvision", "Tax provision"],
    ["netIncomeCommonStockholders", "Net income (common stockholders)"],
    ["dilutedNiAvailableToComStockholders", "Diluted NI available to common stockholders"],
    ["basicEps", "Basic EPS"],
    ["dilutedEps", "Diluted EPS"],
    ["basicAverageShares", "Basic average shares"],
    ["dilutedAverageShares", "Diluted average shares"],
    ["totalOperatingIncomeAsReported", "Total operating income (as reported)"],
    ["totalExpenses", "Total expenses"],
    ["netIncomeFromContinuingAndDiscontinuedOperation", "Net income (continuing & discontinued ops)"],
    ["normalisedIncome", "Normalised income"],
    ["interestIncome", "Interest income"],
    ["interestExpense", "Interest expense"],
    ["netInterestIncome", "Net interest income"],
    ["ebit", "EBIT"],
    ["ebitda", "EBITDA"],
    ["reconciledCostOfRevenue", "Reconciled cost of revenue"],
    ["reconciledDepreciation", "Reconciled depreciation"],
    ["netIncomeFromContinuingOperationNetMinorityInterest", "Net income (cont. ops, net minority interest)"],
    ["totalUnusualItemsExcludingGoodwill", "Total unusual items (excl. goodwill)"],
    ["totalUnusualItems", "Total unusual items"],
    ["normalisedEbitda", "Normalised EBITDA"],
    ["taxRateForCalcs", "Tax rate (for calcs)"],
    ["taxEffectOfUnusualItems", "Tax effect of unusual items"]
];

export default financialGridColumns;